Parameters:

  ServiceName:
    Type: String

  StackName:
    Type: String

  Stage:
    Type: String

Resources:

  DevelopmentIamPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${StackName}-development-policy
      Roles:
        - !Ref DevelopmentIamRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParametersByPath
            Resource:
              - !Sub 'arn:aws:ssm:*:*:parameter/${Stage}/${ServiceName}/*'
              - !Sub 'arn:aws:ssm:*:*:parameter/${ServiceName}/${Stage}/*'

  TeamLeadIamPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${StackName}-lead-policy
      Roles:
        - !Ref TeamLeadIamRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Sub 'arn:aws:secretsmanager:*:*:secret:/dbcreds/application_${ServiceName}-*'
              - !Sub 'arn:aws:secretsmanager:*:*:secret:/${ServiceName}/${Stage}/application-secret-*'
          - Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParametersByPath
              - ssm:PutParameter
            Resource:
              - !Sub 'arn:aws:ssm:*:*:parameter/${Stage}/${ServiceName}/*'
              - !Sub 'arn:aws:ssm:*:*:parameter/${ServiceName}/${Stage}/*'
          - Effect: Allow
            Action:
              - ssm:StartSession
            Resource:
              - 'arn:aws:ec2:*:*:instance/*'
            Condition:
              StringEquals:
                'ec2:ResourceTag/APP': !Sub ${ServiceName}
                'ec2:ResourceTag/STAGE': !Sub ${Stage}

  DevelopmentIamRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${StackName}-development-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: sts:AssumeRole

  TeamLeadIamRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${StackName}-lead-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: sts:AssumeRole